### ISSUE TITLE
Search stalls after looking for first train

### ISSUE THREAD

**Issue by spolcyn** [tikkisean/rail-for-less#1]
Thanks for building this app! Very useful feature to have.

Noticed that searches now fail on searching for the first train, with an error message like:

```
12%
Fetching date 1 of 8
No trains found!
```

An example query to generate that would be NYP -> PHL 1/18/23 to 1/25/23

**Comment by tikkisean** [comment]
Sorry about that, looks like the app was using invalid proxy credentials because my subscription from my proxy provider had expired without notifying me. I just ran your request and it appears to be working now with a fresh set of proxies. There are enough unpredictable variables at play with this site that going forward I might need to implement a status checker that can run test requests at a given interval and notify me of future problems when they occur.

**Comment by redwearer** [comment]
Seeing this issue again I think

**Comment by tikkisean** [comment]
The ongoing CAPTCHA issues are separate from the above issue, you can read more about them in the October 2nd announcement on the site. I just haven't had the time the past couple months to fix this as its an issue fundamental to the way the scraping algorithm is designed, I expect to have the site redesign complete within a month, check dev.railforless.us for the latest progress. In the meantime CAPTCHA will remain an issue except during the very late night hours.
