### ISSUE TITLE
Documentation/Instructions

### ISSUE THREAD

**Issue by luisegarduno** [tikkisean/rail-for-less#4]
Visited the website and saw the repository linked :partying_face:. I was looking for documentation on how to deploy the site locally, and then saw the [windows-dev-instructions](https://github.com/tikkisean/rail-for-less/blob/main/windows-dev-instructions.txt).

Figured I could quickly make the instructions look a bit nicer, so I forked the repo and made the changes (see [here](https://github.com/luisegarduno/rail-for-less/blob/main/windows-dev-instructions.md)). However, after making the changes to the instructions, I then noticed that the instructions themselves are deprecated given that the `client/` & `server/` directories had been removed a while ago.

Are there any specific instructions/requirements for running the main/dev branch locally? I tried running `npm start` but got a couple of errors.

**Comment by tikkisean** [comment]
Hello Luis,

As you pointed out, unfortunately those instructions are deprecated with the latest release. In fact, if you look at the dev branch I'm currently working on you'll see I removed that file—I overlooked it pushing the last update. Before the backend and frontend ran on the same server so you could run the entire site locally, however with this new version of the site we have chosen to keep the backend close source. I might add some instructions to run the frontend repo locally in the future (in the fancy markdown syntax you showcased). Otherwise, I'd be happy to answer any questions you have about the project :).

Best,
Sean
________________________________
From: Luis ***@***.***>
Sent: Saturday, April 13, 2024 11:02 PM
To: tikkisean/rail-for-less ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tikkisean/rail-for-less] Documentation/Instructions (Issue #4)


Visited the website and saw the repository linked 🥳. I was looking for documentation on how to deploy the site locally, and then saw the windows-dev-instructions<https://github.com/tikkisean/rail-for-less/blob/main/windows-dev-instructions.txt>.

Figured I could quickly make the instructions look a bit nicer, so I forked the repo and made the changes (see here<https://github.com/luisegarduno/rail-for-less/blob/main/windows-dev-instructions.md>). However, after making the changes to the instructions, I then noticed that the instructions themselves are deprecated given that the client/ & server/ directories had been removed a while ago.

Are there any specific instructions/requirements for running the main/dev branch locally? I tried running npm start but got a couple of errors.
